name: proto
channels:
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.7.1
  - cudatoolkit=11.0
  - absl-py
  - pyparsing
  - jupyterlab
  - scikit-image
  - pip
  - pip:
    - termcolor
    - git+git://github.com/deepmind/dm_control.git
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - git+git://github.com/facebookresearch/hydra@0.11_branch
    - pandas
    - ipdb
    - tqdm
    - torchvision
    - yapf
    - mujoco_py
    - sklearn
    - matplotlib
    - kornia
    - MakeTreeDir
